# Generated by Django 3.2.4 on 2021-06-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
