# Generated by Django 3.2.4 on 2021-06-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('auth_otp', models.CharField(max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
