# Generated by Django 3.2.4 on 2021-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
